### PR TITLE
Add versioning mechanism

### PR DESCRIPTION
**Pull request by Tal-or**
The version will be defined in build time using ldflags
Identical logic to https://github.com/k8stopologyawareschedwg/resource-topology-exporter/pull/28

In addition, added some missing logic on ```main.go```
This logic was probably removed when we remove docopt here:#19
I added it on the same PR because it required in order for the E2E lane to pass

### CODE REVIEW

**Comment by Tal-or** [comment]
/hold
Depend on #19

**Comment by fromanirh** [comment]
/hold cancel
please fix the failing lane and we can merge this.

**Comment by Tal-or** [comment]
> `With prometheus endpoint configured [BeforeEach] /go/src/github.com/openshift-kni/resource-topology-exporter/vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/metrics.go:66 should have some metrics exported /go/src/github.com/openshift-kni/resource-topology-exporter/vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/metrics.go:67` `Unexpected error:`
> 
> ```
>     <*errors.StatusError | 0xc0007d94a0>: {
>         ErrStatus: {
>             TypeMeta: {Kind: "", APIVersion: ""},
>             ListMeta: {
>                 SelfLink: "",
>                 ResourceVersion: "",
>                 Continue: "",
>                 RemainingItemCount: nil,
>             },
>             Status: "Failure",
>             Message: "unable to parse requirement: <nil>: Invalid value: \"&LabelSelector{MatchLabels:map[string]string{name:\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')",
>             Reason: "BadRequest",
>             Details: nil,
>             Code: 400,
>         },
>     }
>     unable to parse requirement: <nil>: Invalid value: "&LabelSelector{MatchLabels:map[string]string{name:": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
> occurred
> ```
> 
> Which surprisingly does not reproduce on the u/s side. I'm working to fix it as well

The error shown above also fixed in https://github.com/k8stopologyawareschedwg/resource-topology-exporter/pull/60

**Comment by Tal-or** [comment]
/hold 
Depend on k8stopologyawareschedwg/resource-topology-exporter#60

**Pull request merged**
